### ISSUE TITLE
Potential -1 and 1 confusion

### ISSUE THREAD

**Issue by PedroBarcha** [swagster420/Phishing-Url-Detection-Using-Machine-Learning#7]
Hello!
I've realized that your program assigns -1 to some feature when they are considered phishing (like "Having IP Address", "Long URL" and "Using Shortening Services").
Isn't that incorrect?
Thanks in advance

**Comment by Mynkthkr** [comment]
hey i need your help for making this type of project . please help

**Comment by 0xp0tato** [comment]
To everyone

This was my project for 3rd year in college. No work has been done on it since 2018. I would like to thank everyone showing interest in it. Feel free to use this project for yourself. I will not be working on this project anymore.

Regards
0xp0tato
